version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: dependencies install
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
      - run:
          name: run tests
          command: |
              . venv/bin/activate
              pytest -v